[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
bridge-methods = { path = "../methods" }
bridge-core = { path = "../core" }
risc0-zkvm = { version = "0.19.1" }
env_logger = "0.10"
serde = "1.0"
hex = "0.4.3"
serde_json = "1.0.108"

